# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build_images:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: commit push
        run: |
          docker info
          pwd
          ls
      - name: docker login
        run: docker login -p ${{ secrets.REGISTRY_HONGKONG_SECRET }} --username=devops@1148299792416188 registry.cn-hongkong.aliyuncs.com
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y%m%d%H$M')"
      - name: Get commit
        id: commitid
        run: echo "::set-output name=commitid::$(git rev-parse --short HEAD)"
      - name: Build docker image
        run: docker build -t registry.cn-hongkong.aliyuncs.com/merico/table:${{ steps.extract_branch.outputs.branch }}_${{ steps.date.outputs.today }}_${{ steps.date.outputs.commitid }} .
      - name: Push image
        run: docker push registry.cn-hongkong.aliyuncs.com/merico/table:${{ steps.extract_branch.outputs.branch }}_${{ steps.date.outputs.today }}_${{ steps.date.outputs.commitid }}
      
